---
- hosts: all
  roles:
  - role: '{{ playbook_dir }}'
    packer_plugin_name: builder-vsphere-iso
    packer_plugin_ver: v2.3
    packer_plugin_mirror: https://github.com/jetbrains-infra/packer-builder-vsphere/releases/download
    packer_plugin_checksums:
      v2.3:
        # https://github.com/jetbrains-infra/packer-builder-vsphere/releases/download/v2.3/packer-builder-vsphere-iso.exe
        windows: sha256:26f1c2f8b57660f230778d23f6a4aa6b5d1ebccf83099e3991e260ff05989974
        # https://github.com/jetbrains-infra/packer-builder-vsphere/releases/download/v2.3/packer-builder-vsphere-iso.linux
        linux: sha256:6e432cc39503ac6604564ba33aaf10d7debb6b6d20429b0af168a00bee342c3b
        # https://github.com/jetbrains-infra/packer-builder-vsphere/releases/download/v2.3/packer-builder-vsphere-iso.macos
        macos: sha256:5a435c0d83ec6f9aa85948b8da006b35ebb3b91b9647795c47819f1c7100091e
  - role: '{{ playbook_dir }}'
    packer_plugin_name: builder-vsphere-clone
    packer_plugin_ver: v2.3
    packer_plugin_mirror: https://github.com/jetbrains-infra/packer-builder-vsphere/releases/download
    packer_plugin_checksums:
      v2.3:
        # https://github.com/jetbrains-infra/packer-builder-vsphere/releases/download/v2.3/packer-builder-vsphere-clone.exe
        windows: sha256:bdd0681ec78d4af4d9b2940e82a089d3c1b8a93af48548f69646781bc8b10989
        # https://github.com/jetbrains-infra/packer-builder-vsphere/releases/download/v2.3/packer-builder-vsphere-clone.linux
        linux: sha256:6aea5b003bbdfbe8f7948dd6c905e224f8fe6b94ed9ccbf46917b01e1a0d8e70
        # https://github.com/jetbrains-infra/packer-builder-vsphere/releases/download/v2.3/packer-builder-vsphere-clone.macos
        macos: sha256:13f56c1bc099c4d372573c0f5aa9bf7cf85a79d37333e38d59a76e4918755e4c
